In [1]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('FCC_US_state_filings.csv',encoding = 'latin-1')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [22]:
#select
df = df[['State_Abbreviation','id','date_submission','contact_email']]

In [23]:
df.head(20)

,State_Abbreviation,id,date_submission,contact_email
0,IA,59f8b2bb50b733300f069dce,2017-07-11T15:53:55.588Z,LINDAKUNZE88@GMAIL.COM
1,RI,59f8b2bb50b733300f069dd1,2017-07-11T15:53:55.750Z,TD3ONE@GMAIL.COM
2,PA,59f8b2bb50b733300f06a0cf,2017-07-11T15:54:43.314Z,TJ-VANTASSEL@HOTMAIL.COM
3,MI,59f8b2bb50b733300f06a0df,2017-07-11T15:54:44.053Z,NIKKISHERLEY@GMAIL.COM
4,NY,59f8b2bb50b733300f06a0e7,2017-07-11T15:54:44.444Z,PAULAMUTTER61@GMAIL.COM
5,AZ,59f8b2bb50b733300f06a0eb,2017-07-11T15:54:44.620Z,SOCHIE023@HOTMAIL.COM
6,NY,59f8b2bb50b733300f06a0f7,2017-07-11T15:54:45.230Z,ROBIEGRAVES30@GMAIL.COM
7,LA,59f8b2bb50b733300f06a0fa,2017-07-11T15:54:45.283Z,TONYMALNAR@YAHOO.COM
8,AL,59f8b2eb50b733300f06a6e7,2017-07-11T15:56:16.537Z,DLB4318@GMAIL.COM
9,PA,59f8b2eb50b733300f06a6ee,2017-07-11T15:56:17.077Z,NaN
10,OH,59f8b2eb50b733300f06a6f2,2017-07-11T15:56:17.287Z,NEWTONC@YAHOO.COM
11,AL,59f8b2eb50b733300f06a6f4,2017-07-11T15:56:17.293Z,ALFORDMAN13@YAHOO.COM
12,IL,59f8b2eb50b733300f06a705,2017-07-11T15:56:17.938Z,NaN
13,MI,59f8b2eb50b733300f06a47e,2017-07-11T15:55:40.122Z,STEVENTORRES85@HOTMAIL.COM
14,WV,59f8b2eb50b733300f06a481,2017-07-11T15:55:40.381Z,AV262190@GMAIL.COM
15,FL,59f8b2eb50b733300f06a48a,2017-07-11T15:55:40.976Z,SJONES9611@YAHOO.COM
16,IN,59f8b2eb50b733300f06a49e,2017-07-11T15:55:41.907Z,ZACHSTYLE551@YAHOO.COM
17,OK,59f8b2eb50b733300f06a4a0,2017-07-11T15:55:41.933Z,YOGI2004@YAHOO.COM
18,AR,59f8b2eb50b733300f06a4a1,2017-07-11T15:55:41.985Z,GDEATON@KINCO.NET
19,FL,59f8b2bb50b733300f069ddd,2017-07-11T15:53:56.569Z,PANDIT_MELARAM@HOTMAIL.COM

In [24]:
#remove NaN's
df = df[df['contact_email'].notnull()]

In [25]:
#convert to strings
df['contact_email'] = df['contact_email'].astype(str)

In [26]:
#count
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1511016 entries, 0 to 2339764
Data columns (total 4 columns):
State_Abbreviation    1498771 non-null object
id                    1511016 non-null object
date_submission       1511016 non-null object
contact_email         1511016 non-null object
dtypes: object(4)
memory usage: 57.6+ MB

In [29]:
#inspect
df.head(3)

,State_Abbreviation,id,date_submission,contact_email
0,IA,59f8b2bb50b733300f069dce,2017-07-11T15:53:55.588Z,LINDAKUNZE88@GMAIL.COM
1,RI,59f8b2bb50b733300f069dd1,2017-07-11T15:53:55.750Z,TD3ONE@GMAIL.COM
2,PA,59f8b2bb50b733300f06a0cf,2017-07-11T15:54:43.314Z,TJ-VANTASSEL@HOTMAIL.COM

In [31]:
df = df[df['contact_email'].str.contains('@')]

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1510965 entries, 0 to 2339764
Data columns (total 4 columns):
State_Abbreviation    1498750 non-null object
id                    1510965 non-null object
date_submission       1510965 non-null object
contact_email         1510965 non-null object
dtypes: object(4)
memory usage: 57.6+ MB

In [56]:
#define function to get domain name from string
def get_domain (y):
    """Takes domain name string field """
    #reg = re.compile('\d{5}')
    #z = reg.findall(y)
    z = y.split('@')
    
    if len(z) == 1:
        return None
    else:
        return z[1]

In [60]:
df['domain'] = df['contact_email'].apply(get_domain)

In [61]:
df

,State_Abbreviation,id,date_submission,contact_email,domain
0,IA,59f8b2bb50b733300f069dce,2017-07-11T15:53:55.588Z,LINDAKUNZE88@GMAIL.COM,GMAIL.COM
1,RI,59f8b2bb50b733300f069dd1,2017-07-11T15:53:55.750Z,TD3ONE@GMAIL.COM,GMAIL.COM
2,PA,59f8b2bb50b733300f06a0cf,2017-07-11T15:54:43.314Z,TJ-VANTASSEL@HOTMAIL.COM,HOTMAIL.COM
3,MI,59f8b2bb50b733300f06a0df,2017-07-11T15:54:44.053Z,NIKKISHERLEY@GMAIL.COM,GMAIL.COM
4,NY,59f8b2bb50b733300f06a0e7,2017-07-11T15:54:44.444Z,PAULAMUTTER61@GMAIL.COM,GMAIL.COM
5,AZ,59f8b2bb50b733300f06a0eb,2017-07-11T15:54:44.620Z,SOCHIE023@HOTMAIL.COM,HOTMAIL.COM
6,NY,59f8b2bb50b733300f06a0f7,2017-07-11T15:54:45.230Z,ROBIEGRAVES30@GMAIL.COM,GMAIL.COM
7,LA,59f8b2bb50b733300f06a0fa,2017-07-11T15:54:45.283Z,TONYMALNAR@YAHOO.COM,YAHOO.COM
8,AL,59f8b2eb50b733300f06a6e7,2017-07-11T15:56:16.537Z,DLB4318@GMAIL.COM,GMAIL.COM
10,OH,59f8b2eb50b733300f06a6f2,2017-07-11T15:56:17.287Z,NEWTONC@YAHOO.COM,YAHOO.COM
11,AL,59f8b2eb50b733300f06a6f4,2017-07-11T15:56:17.293Z,ALFORDMAN13@YAHOO.COM,YAHOO.COM
13,MI,59f8b2eb50b733300f06a47e,2017-07-11T15:55:40.122Z,STEVENTORRES85@HOTMAIL.COM,HOTMAIL.COM
14,WV,59f8b2eb50b733300f06a481,2017-07-11T15:55:40.381Z,AV262190@GMAIL.COM,GMAIL.COM
15,FL,59f8b2eb50b733300f06a48a,2017-07-11T15:55:40.976Z,SJONES9611@YAHOO.COM,YAHOO.COM
16,IN,59f8b2eb50b733300f06a49e,2017-07-11T15:55:41.907Z,ZACHSTYLE551@YAHOO.COM,YAHOO.COM
17,OK,59f8b2eb50b733300f06a4a0,2017-07-11T15:55:41.933Z,YOGI2004@YAHOO.COM,YAHOO.COM
18,AR,59f8b2eb50b733300f06a4a1,2017-07-11T15:55:41.985Z,GDEATON@KINCO.NET,KINCO.NET
19,FL,59f8b2bb50b733300f069ddd,2017-07-11T15:53:56.569Z,PANDIT_MELARAM@HOTMAIL.COM,HOTMAIL.COM
20,OR,59f8b2bb50b733300f069de0,2017-07-11T15:53:56.820Z,ABALOS12345@GMAIL.COM,GMAIL.COM
21,VA,59f8b2bb50b733300f069ded,2017-07-11T15:53:57.699Z,RICKYSTEEN4@GMAIL.COM,GMAIL.COM
22,FL,59f8b2bb50b733300f069df2,2017-07-11T15:53:58.066Z,SA_WAREHAM@YAHOO.COM,YAHOO.COM
23,IA,59f8b2bb50b733300f069df6,2017-07-11T15:53:58.386Z,BLUEDRAGON2132@GMAIL.COM,GMAIL.COM
24,MN,59f8b2bb50b733300f069df9,2017-07-11T15:53:58.442Z,SPRUITT885SP@GMAIL.COM,GMAIL.COM
25,VA,59f8b2bb50b733300f069e01,2017-07-11T15:53:58.961Z,BOOSHY24@GMAIL.COM,GMAIL.COM
26,CA,59f8b2bb50b733300f069e02,2017-07-11T15:53:58.977Z,SANYUSS@ICLOUD.COM,ICLOUD.COM
27,AL,59f8b2bb50b733300f069e04,2017-07-11T15:53:59.150Z,ALABAMALMK@YAHOO.COM,YAHOO.COM
28,GA,59f8b2bb50b733300f069e0b,2017-07-11T15:53:59.521Z,PICKETTDAVIDA60@YAHOO.COM,YAHOO.COM
29,TX,59f8b2bb50b733300f06a10b,2017-07-11T15:54:46.230Z,HALEYYMARIEE58@GMAIL.COM,GMAIL.COM
30,VA,59f8b2bb50b733300f06a10c,2017-07-11T15:54:46.236Z,KASSIEKRUBACK@HOTMAIL.COM,HOTMAIL.COM
31,AL,59f8b2bb50b733300f06a111,2017-07-11T15:54:46.695Z,PBRM56@YAHOO.COM,YAHOO.COM
...,...,...,...,...,...
2339733,IL,59f8bdfa50b733300f0ea36c,2017-07-12T08:47:12.130Z,ProkhorButusov@hurra.de,hurra.de
2339734,IL,59f8bdfa50b733300f0ea96e,2017-07-12T05:07:19.941Z,kmillerclc@Hotmail.com,Hotmail.com
2339735,PA,59f8bdfa50b733300f0ea8a1,2017-07-12T08:47:17.682Z,FatimaKirillova@hurra.de,hurra.de
2339736,MI,59f8bdfa50b733300f0eb1ee,2017-07-12T08:47:16.602Z,VladislavKruglov@hurra.de,hurra.de
2339737,CO,59f8bdfa50b733300f0eac57,2017-07-12T08:47:09.865Z,SamuelYuriev@hurra.de,hurra.de
2339738,NJ,59f8bdfa50b733300f0eb7b5,2017-07-12T08:47:15.542Z,CyrusSergeyeva@hurra.de,hurra.de
2339739,WI,59f8be3150b733300f0ec1e1,2017-07-12T08:46:29.550Z,GoldenBalashova@hurra.de,hurra.de
2339740,NC,59f8be3150b733300f0ec5e3,2017-07-12T08:47:19.219Z,JaroslavAndreev@hurra.de,hurra.de
2339741,VA,59f8be3150b733300f0ec616,2017-07-12T08:46:28.546Z,IgnatVoronov@hurra.de,hurra.de
2339742,MI,59f8be3150b733300f0ec8ef,2017-07-12T08:47:11.092Z,GoldenBaranova@hurra.de,hurra.de
2339743,IL,59f8be3150b733300f0eca36,2017-07-12T08:47:12.632Z,ElenaYefremova@hurra.de,hurra.de
2339744,GA,59f8be3250b733300f0ece42,2017-07-12T08:47:03.209Z,EdgarVinogradov@hurra.de,hurra.de
2339745,MO,59f8be3150b733300f0ecb9b,2017-07-12T08:47:24.168Z,LuciaMuravyova@hurra.de,hurra.de
2339746,IL,59f8be3150b733300f0ecc66,2017-07-12T08:47:22.444Z,AlbertTokaryev@hurra.de,hurra.de
2339747,FL,59f8be3250b733300f0ed8af,2017-07-12T08:47:47.740Z,SabineKazantseva@hurra.de,hurra.de
2339748,OK,59f8be3250b733300f0edac6,2017-07-12T08:47:10.279Z,ArkhipZhdanov@hurra.de,hurra.de
2339749,FL,59f8be6e50b733300f0ee41c,2017-07-12T08:47:12.693Z,CleopatraAksyonova@hurra.de,hurra.de
2339750,MO,59f8be3250b733300f0edf78,2017-07-12T08:46:55.877Z,ValeriyaSamoylova@hurra.de,hurra.de
2339751,VA,59f8be3250b733300f0edfcf,2017-07-12T08:47:15.707Z,NestorBazhenov@hurra.de,hurra.de
2339752,IL,59f8c7d650b733300f1703e2,2017-07-12T14:09:38.523Z,crew1232@outlook.com,outlook.com
2339753,FL,59f8cb1150b733300f197833,2017-07-12T18:39:02.369Z,Kingoftehderpslol@gmail.com,gmail.com
2339754,FL,59f8cb1150b733300f197986,2017-07-12T18:39:49.064Z,Kingoftehderpslol@gmail.com,gmail.com
2339756,IA,59f8cf4c50b733300f1c7898,2017-07-12T22:42:03.808Z,adrianmeza019@gmail.com,gmail.com
2339757,CA,59f8d36350b733300f1f6285,2017-07-13T01:49:20.729Z,jcoleman16@mail.csuchico.edu,mail.csuchico.edu
2339758,CA,59f8d36350b733300f1f6286,2017-07-13T01:49:20.730Z,jcoleman16@mail.csuchico.edu,mail.csuchico.edu
2339759,CA,59f8d36350b733300f1f628a,2017-07-13T01:49:20.985Z,jcoleman16@mail.csuchico.edu,mail.csuchico.edu
2339760,OH,59f8d3c550b733300f1fb22e,2017-07-13T02:22:05.659Z,acrum7@kent.edu,kent.edu
2339762,WI,59f8d45d50b733300f2029fe,2017-07-13T03:17:05.640Z,pkeldsen@gmail.com,gmail.com
2339763,WA,59f8d49150b733300f20571d,2017-07-13T03:40:00.562Z,fmcorey@gmail.com,gmail.com
2339764,MI,59f8dc3d50b733300f268bbb,2017-07-14T08:45:08.036Z,alanbouwman1998@gmail.com,gmail.com

In [66]:
df = df.dropna()
df.head(10)

,State_Abbreviation,id,date_submission,contact_email,domain
0,IA,59f8b2bb50b733300f069dce,2017-07-11T15:53:55.588Z,LINDAKUNZE88@GMAIL.COM,gmail.com
1,RI,59f8b2bb50b733300f069dd1,2017-07-11T15:53:55.750Z,TD3ONE@GMAIL.COM,gmail.com
2,PA,59f8b2bb50b733300f06a0cf,2017-07-11T15:54:43.314Z,TJ-VANTASSEL@HOTMAIL.COM,hotmail.com
3,MI,59f8b2bb50b733300f06a0df,2017-07-11T15:54:44.053Z,NIKKISHERLEY@GMAIL.COM,gmail.com
4,NY,59f8b2bb50b733300f06a0e7,2017-07-11T15:54:44.444Z,PAULAMUTTER61@GMAIL.COM,gmail.com
5,AZ,59f8b2bb50b733300f06a0eb,2017-07-11T15:54:44.620Z,SOCHIE023@HOTMAIL.COM,hotmail.com
6,NY,59f8b2bb50b733300f06a0f7,2017-07-11T15:54:45.230Z,ROBIEGRAVES30@GMAIL.COM,gmail.com
7,LA,59f8b2bb50b733300f06a0fa,2017-07-11T15:54:45.283Z,TONYMALNAR@YAHOO.COM,yahoo.com
8,AL,59f8b2eb50b733300f06a6e7,2017-07-11T15:56:16.537Z,DLB4318@GMAIL.COM,gmail.com
10,OH,59f8b2eb50b733300f06a6f2,2017-07-11T15:56:17.287Z,NEWTONC@YAHOO.COM,yahoo.com

In [67]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1498750 entries, 0 to 2339764
Data columns (total 5 columns):
State_Abbreviation    1498750 non-null object
id                    1498750 non-null object
date_submission       1498750 non-null object
contact_email         1498750 non-null object
domain                1498750 non-null object
dtypes: object(5)
memory usage: 68.6+ MB

In [68]:
df['domain'] = df['domain'].str.lower()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [65]:
df.head()

,State_Abbreviation,id,date_submission,contact_email,domain
0,IA,59f8b2bb50b733300f069dce,2017-07-11T15:53:55.588Z,LINDAKUNZE88@GMAIL.COM,gmail.com
1,RI,59f8b2bb50b733300f069dd1,2017-07-11T15:53:55.750Z,TD3ONE@GMAIL.COM,gmail.com
2,PA,59f8b2bb50b733300f06a0cf,2017-07-11T15:54:43.314Z,TJ-VANTASSEL@HOTMAIL.COM,hotmail.com
3,MI,59f8b2bb50b733300f06a0df,2017-07-11T15:54:44.053Z,NIKKISHERLEY@GMAIL.COM,gmail.com
4,NY,59f8b2bb50b733300f06a0e7,2017-07-11T15:54:44.444Z,PAULAMUTTER61@GMAIL.COM,gmail.com

In [70]:
# sorting email domains group by state
s = df['domain'].groupby(df['State_Abbreviation']).value_counts()

In [71]:
s

State_Abbreviation  domain
AK                  gmail.com               1467
                    yahoo.com                657
                    hotmail.com              332
                    hurra.de                 134
                    gci.net                   80
                    aol.com                   57
                    superrito.com             51
                    dayrep.com                49
                    armyspy.com               48
                    jourrapide.com            46
                    fleckens.hu               43
                    icloud.com                40
                    live.com                  38
                    outlook.com               36
                    gustr.com                 34
                    alaska.net                33
                    teleworm.us               30
                    cuvox.de                  29
                    mtaonline.net             24
                    alaska.edu                23
                    einrot.com                23
                    rhyta.com                 21
                    me.com                    19
                    msn.com                   19
                    ymail.com                 17
                    acsalaska.net             11
                    mail.com                   9
                    ak.net                     8
                    comcast.net                8
                    kpunet.net                 8
                                            ...
WY                  netzero.net                1
                    nglconnection.net          1
                    none.com                   1
                    nordnet.fr                 1
                    numail.org                 1
                    pornhub.com                1
                    port.ac.uk                 1
                    posteo.net                 1
                    protonmail.com             1
                    q.com                      1
                    qwestoffice.net            1
                    rapidnet.com               1
                    rossiter.com               1
                    sheridan.edu               1
                    sprynet.com                1
                    student.lccc.wy.edu        1
                    sweetwaterhsa.com          1
                    tcinc.net                  1
                    tklein.com                 1
                    tribcsp.com                1
                    uc.edu                     1
                    verizon.net                1
                    vxn.com                    1
                    web.de                     1
                    wildblue.net               1
                    wimberg.com                1
                    wittstock.us               1
                    wooyek.com                 1
                    wyomingcreations           1
                    wyomingcreations.com       1
Name: domain, Length: 41209, dtype: int64

In [72]:
df2 = s.groupby(level=0).nlargest(5)

In [73]:
df3 = pd.DataFrame(df2)

In [76]:
df3.head(20)

                                                     domain
State_Abbreviation State_Abbreviation domain
AK                 AK                 gmail.com        1467
                                      yahoo.com         657
                                      hotmail.com       332
                                      hurra.de          134
                                      gci.net            80
AL                 AL                 gmail.com       13721
                                      yahoo.com        5520
                                      aol.com          1241
                                      hotmail.com      1055
                                      bellsouth.net     597
AP                 AP                 gmail.com           2
AR                 AR                 gmail.com        6925
                                      yahoo.com        3597
                                      hotmail.com       715
                                      aol.com           353
                                      hurra.de          303
AZ                 AZ                 gmail.com       13902
                                      yahoo.com        5517
                                      hotmail.com      1933
                                      cox.net          1844

In [77]:
df3.index = df3.index.set_names(['index','state', 'email_domain'])

In [78]:
df3.reset_index(inplace=True)

In [79]:
df3.head(20)

   index state   email_domain  domain
0     AK    AK      gmail.com    1467
1     AK    AK      yahoo.com     657
2     AK    AK    hotmail.com     332
3     AK    AK       hurra.de     134
4     AK    AK        gci.net      80
5     AL    AL      gmail.com   13721
6     AL    AL      yahoo.com    5520
7     AL    AL        aol.com    1241
8     AL    AL    hotmail.com    1055
9     AL    AL  bellsouth.net     597
10    AP    AP      gmail.com       2
11    AR    AR      gmail.com    6925
12    AR    AR      yahoo.com    3597
13    AR    AR    hotmail.com     715
14    AR    AR        aol.com     353
15    AR    AR       hurra.de     303
16    AZ    AZ      gmail.com   13902
17    AZ    AZ      yahoo.com    5517
18    AZ    AZ    hotmail.com    1933
19    AZ    AZ        cox.net    1844

In [80]:
del df3['index']

In [81]:
df3.rename(columns={'domain':'count'}, inplace=True)

In [83]:
df3.head(11)

   state   email_domain  count
0     AK      gmail.com   1467
1     AK      yahoo.com    657
2     AK    hotmail.com    332
3     AK       hurra.de    134
4     AK        gci.net     80
5     AL      gmail.com  13721
6     AL      yahoo.com   5520
7     AL        aol.com   1241
8     AL    hotmail.com   1055
9     AL  bellsouth.net    597
10    AP      gmail.com      2

In [84]:
df3.to_csv('FCC_domain_top_5_by_state.csv',index=False)

In [87]:
# generate email count distribution:
df.head()

,State_Abbreviation,id,date_submission,contact_email,domain
0,IA,59f8b2bb50b733300f069dce,2017-07-11T15:53:55.588Z,LINDAKUNZE88@GMAIL.COM,gmail.com
1,RI,59f8b2bb50b733300f069dd1,2017-07-11T15:53:55.750Z,TD3ONE@GMAIL.COM,gmail.com
2,PA,59f8b2bb50b733300f06a0cf,2017-07-11T15:54:43.314Z,TJ-VANTASSEL@HOTMAIL.COM,hotmail.com
3,MI,59f8b2bb50b733300f06a0df,2017-07-11T15:54:44.053Z,NIKKISHERLEY@GMAIL.COM,gmail.com
4,NY,59f8b2bb50b733300f06a0e7,2017-07-11T15:54:44.444Z,PAULAMUTTER61@GMAIL.COM,gmail.com

In [88]:
email_counts = df['domain'].value_counts()

In [90]:
email_counts.head(30)

gmail.com         671274
yahoo.com         285072
hotmail.com        81084
aol.com            73249
comcast.net        31539
hurra.de           28660
msn.com            15522
att.net            14070
sbcglobal.net      13708
icloud.com         13668
outlook.com        10354
live.com           10050
verizon.net         9343
fleckens.hu         9192
einrot.com          9177
jourrapide.com      9161
cuvox.de            9048
rhyta.com           8943
superrito.com       8913
dayrep.com          8866
armyspy.com         8851
gustr.com           8801
teleworm.us         8676
cox.net             7260
bellsouth.net       6817
me.com              5347
charter.net         4814
earthlink.net       4802
ymail.com           4649
pornhub.com         4488
Name: domain, dtype: int64

In [92]:
email_counts.to_csv('FCC_domain_email_counts.csv',index=False)

In [93]:
df.to_csv('FCC_domain_date_submission.csv',index=False)

In [3]:
df_top5_per_states = pd.read_csv('FCC_domain_top_5_by_state2.csv')

In [6]:
df_top5_per_states.head(16)

   state   email_domain  count    rank
0     AK      gmail.com   1467   First
1     AK      yahoo.com    657  Second
2     AK    hotmail.com    332   Third
3     AK       hurra.de    134  Fourth
4     AK        gci.net     80   Fifth
5     AL      gmail.com  13721   First
6     AL      yahoo.com   5520  Second
7     AL        aol.com   1241   Third
8     AL    hotmail.com   1055  Fourth
9     AL  bellsouth.net    597   Fifth
10    AR      gmail.com   6925   First
11    AR      yahoo.com   3597  Second
12    AR    hotmail.com    715   Third
13    AR        aol.com    353  Fourth
14    AR       hurra.de    303   Fifth
15    AZ      gmail.com  13902   First

In [26]:
df_top5_per_states['domain_count'] = df_top5_per_states['email_domain'] + " : " + df_top5_per_states['count'].astype(str)

In [10]:
df_top5_per_states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 4 columns):
state           260 non-null object
email_domain    260 non-null object
count           260 non-null int64
rank            260 non-null object
dtypes: int64(1), object(3)
memory usage: 8.2+ KB

In [17]:
df_top5_per_states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 4 columns):
state           260 non-null object
email_domain    260 non-null object
count           260 non-null int64
rank            260 non-null object
dtypes: int64(1), object(3)
memory usage: 8.2+ KB

In [27]:
df_ranked = df_top5_per_states.set_index(['state', 'rank'])['domain_count'].unstack().reset_index()

In [28]:
df_ranked.to_csv('FCC_df_ranked.csv',index=False)

In [29]:
df_ranked.head()

rank,state,Fifth,First,Fourth,Second,Third
0,AK,gci.net : 80,gmail.com : 1467,hurra.de : 134,yahoo.com : 657,hotmail.com : 332
1,AL,bellsouth.net : 597,gmail.com : 13721,hotmail.com : 1055,yahoo.com : 5520,aol.com : 1241
2,AR,hurra.de : 303,gmail.com : 6925,aol.com : 353,yahoo.com : 3597,hotmail.com : 715
3,AZ,aol.com : 1381,gmail.com : 13902,cox.net : 1844,yahoo.com : 5517,hotmail.com : 1933
4,CA,sbcglobal.net : 4670,gmail.com : 80325,aol.com : 7996,yahoo.com : 34318,hotmail.com : 9089